In [ ]:
import numpy as np
x = np.random.rand(5)
D = x[:, np.newaxis] - x[np.newaxis, :]

print(D)
# Extra task
x = np.array([1, 2, 3, 4, 5])
a=x[:, np.newaxis]
print(a)
b= x[np.newaxis, :]
print(b)
D=a-b
print(D)


[[ 0.          0.14493896  0.56785555  0.47307128  0.40164426]
 [-0.14493896  0.          0.42291659  0.32813233  0.2567053 ]
 [-0.56785555 -0.42291659  0.         -0.09478427 -0.16621129]
 [-0.47307128 -0.32813233  0.09478427  0.         -0.07142702]
 [-0.40164426 -0.2567053   0.16621129  0.07142702  0.        ]]
[[1]
 [2]
 [3]
 [4]
 [5]]
[[1 2 3 4 5]]
[[ 0 -1 -2 -3 -4]
 [ 1  0 -1 -2 -3]
 [ 2  1  0 -1 -2]
 [ 3  2  1  0 -1]
 [ 4  3  2  1  0]]
