In [1]:
import numpy as np


In [2]:
#Task: to interchange rows i and j of a numpy array A.


In [3]:
def swaprow(i, j, A): #defination of swaprow taking argumunt i , j and A numpy array
  tmp = A[i, :]  #  creating a variable tmp and i stored the ith row of numpy array  in that
  A[i, :] = A[j, :] # Here i am storing the j th row in ith row
  A[j, :] = tmp # now we stored the tmp in jth row
ar_dia=np.eye(3)
print('Result before  swaprow follows:',ar_dia,sep='\n')
swaprow(0,1,ar_dia)
print('Result after swaprow follows:',ar_dia,sep='\n')

Result before  swaprow follows:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Result after swaprow follows:
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
