In [ ]:
import numpy as np
from scipy.linalg import svd,qr

In [ ]:
# define the matrix
A = np.array([[1, -2, 3, -3], [2, -4, 9, -2], [-3, 6, -9, 9]])
np.set_printoptions(precision=3, suppress=True)
# calculation of svd matrix
u, s, vh = svd(A)
# Display the results
print("Matrix A:")
print(A)
print("\nLeft Singular Vector Matrix u:")
print(u)
print("\nSingular Values (s):")
print(s)
print("\nConjugate Transpose of Right Singular Vector Matrix (vh):")
print(vh)
print("The matrix ranK of A is : ",np.linalg.matrix_rank(A))
# Extract the basis of the range space from the left singular vectors (u)
#basis_range_space = u[:, :np.count_nonzero(s)]
#np.count_nonzero(s) calculates the number of non-zero singular values in the vector s.
#Since the basis of the range space consists of the columns of u corresponding to non-zero singular values, this count gives you the number of columns you need to extract.
basis_range_space = []
for i in range(len(s)):
    if s[i]!=0:
        basis_range_space.append(u[:, i])

basis_range_space = np.column_stack(basis_range_space)
print("\nBasis of Range Space:")
print(basis_range_space)
print('\n Basis of range space of matrix A using qr decomposition :')
# calculation of qr matrix
u, s = qr(A)
# Display the results
print("Matrix A:")
print(A)
print("\nLeft Singular Vector Matrix u:")
print(u)
print("\nSingular Values (s):")
print(s)
range_space_basis = u
print('\n range_space_basis:')
print(range_space_basis)




Matrix A:
[[ 1 -2  3 -3]
 [ 2 -4  9 -2]
 [-3  6 -9  9]]

Left Singular Vector Matrix u:
[[ 0.266  0.171  0.949]
 [ 0.54  -0.842 -0.   ]
 [-0.799 -0.512  0.316]]

Singular Values (s):
[17.809  4.224  0.   ]

Conjugate Transpose of Right Singular Vector Matrix (vh):
[[ 0.21  -0.42   0.721 -0.509]
 [ 0.005 -0.011 -0.582 -0.813]
 [-0.242 -0.897 -0.296  0.222]
 [ 0.947 -0.136 -0.232  0.174]]
The matrix ranK of A is :  2

Basis of Range Space:
[[ 0.266  0.171  0.949]
 [ 0.54  -0.842 -0.   ]
 [-0.799 -0.512  0.316]]

 Basis of range space of matrix A using qr decomposition :
Matrix A:
[[ 1 -2  3 -3]
 [ 2 -4  9 -2]
 [-3  6 -9  9]]

Left Singular Vector Matrix u:
[[-0.267  0.956 -0.12 ]
 [-0.535 -0.044  0.844]
 [ 0.802  0.289  0.523]]

Singular Values (s):
[[ -3.742   7.483 -12.829   9.087]
 [  0.     -0.     -0.132  -0.176]
 [  0.      0.      2.532   3.376]]

 range_space_basis:
[[-0.267  0.956 -0.12 ]
 [-0.535 -0.044  0.844]
 [ 0.802  0.289  0.523]]


In [ ]:
import numpy as np

# Define the matrix A
A = np.array([[1, -2, 3, -3], [2, -4, 9, -2], [-3, 6, -9, 9]])

# Perform SVD
u, s, vh = np.linalg.svd(A)

# Extract the basis of the range space from SVD
bases_1 = []
for i in range(len(s)):
    if s[i] != 0:
        bases_1.append(u[:, i])
bases_1 = np.column_stack(bases_1)

# Calculate the basis of the range space using QR decomposition
q, r = np.linalg.qr(A)
bases_2 = q
# Check if basis1 can be expressed as a linear combination of basis2
try:
    x = np.linalg.solve(bases_2, bases_1)
    is_same_space = True
except np.linalg.LinAlgError:
    is_same_space = False

if is_same_space:
    print("The spaces spanned by basis1 and basis2 are the same.")
else:
    print("The spaces spanned by basis1 and basis2 are not the same.")



The spaces spanned by basis1 and basis2 are the same.


In [ ]:
import numpy as np
from scipy.linalg import svd, qr
import timeit

# Define the random matrix A of size 500x500
A = np.random.rand(500, 500)

# Function to perform SVD and measure execution time
def svd_timing():
    u, s, vh = np.linalg.svd(A)

# Function to calculate QR and measure execution time
def qr_timing():
    u, s = qr(A)

# Measure execution time for SVD
time_to_solve_svd = timeit.timeit(svd_timing, number=1)
print("Total time to solve using SVD method:", time_to_solve_svd)

# Measure execution time for QR
time_to_solve_qr = timeit.timeit(qr_timing, number=1)
print("Total time to solve using QR method:", time_to_solve_qr)

if time_to_solve_svd >= time_to_solve_qr:
    print("Method QR is faster than SVD")
else:
    print("Method SVD is faster than QR")


Total time to solve using SVD method: 0.14668724900002417
Total time to solve using QR method: 0.039049193000209925
Method QR is faster than SVD
