In [9]:
# find nullspace using SVD
import numpy as np
from scipy.linalg import svd, qr
A = np.array([[1, -2, 9, 5, 4,], [1, -1, 6, 5, -3], [-2, 0, -6, 1, -2],
[4, 1, 9, 1, -9]])
np.set_printoptions(precision=3, suppress=True)
# calculation of svd matrix
u, s, vh = svd(A)
# Display the results
print("Matrix A:")
print(A)
print("\nLeft Singular Vector Matrix u:")
print(u)
print("\nSingular Values (s):")
print(s)
print("\nConjugate Transpose of Right Singular Vector Matrix (vh):")
print(vh)
rank_A=np.linalg.matrix_rank(A)
print("The matrix ranK of A is : ",np.linalg.matrix_rank(A))

null_space = vh[rank_A:].T
print(" null space of A:")
print(null_space)





Matrix A:
[[ 1 -2  9  5  4]
 [ 1 -1  6  5 -3]
 [-2  0 -6  1 -2]
 [ 4  1  9  1 -9]]

Left Singular Vector Matrix u:
[[ 0.498  0.72  -0.106  0.471]
 [ 0.459  0.009 -0.618 -0.638]
 [-0.283 -0.261 -0.758  0.527]
 [ 0.679 -0.643  0.18   0.305]]

Singular Values (s):
[17.208 10.145  4.995  0.   ]

Conjugate Transpose of Right Singular Vector Matrix (vh):
[[ 0.246 -0.045  0.874  0.301 -0.287]
 [-0.13  -0.206  0.229  0.271  0.903]
 [ 0.303  0.202  0.302 -0.84   0.265]
 [-0.872  0.357  0.291 -0.147 -0.074]
 [ 0.265  0.887 -0.088  0.329  0.165]]
The matrix ranK of A is :  3
 null space of A:
[[-0.872  0.265]
 [ 0.357  0.887]
 [ 0.291 -0.088]
 [-0.147  0.329]
 [-0.074  0.165]]


In [10]:
#Find the null space of the same matrix A using the QR
import numpy as np
from scipy.linalg import svd, qr
A = np.array([[1, -2, 9, 5, 4,], [1, -1, 6, 5, -3], [-2, 0, -6, 1, -2],
[4, 1, 9, 1, -9]])
np.set_printoptions(precision=3, suppress=True)
# calculation of QR  matrix
Q, R = qr(A)
# Display the results
print("Matrix A:")
print(A)
print("\n Matrix Q:")
print(Q)
print(" matrix R :")
print(R)

rank_A=np.linalg.matrix_rank(A)
print("The matrix ranK of A is : ",np.linalg.matrix_rank(A))

null_space = Q[:,rank_A:]
print("Basis for the null space of A:")
print(null_space)

Matrix A:
[[ 1 -2  9  5  4]
 [ 1 -1  6  5 -3]
 [-2  0 -6  1 -2]
 [ 4  1  9  1 -9]]

 Matrix Q:
[[-0.213 -0.838  0.317 -0.389]
 [-0.213 -0.428 -0.779  0.405]
 [ 0.426  0.037 -0.522 -0.738]
 [-0.853  0.335 -0.145 -0.373]]
 matrix R :
[[ -4.69   -0.213 -13.432  -2.558   6.609]
 [  0.      2.44   -7.321  -5.961  -5.16 ]
 [  0.      0.      0.     -2.977   5.954]
 [  0.      0.      0.     -1.03    2.061]]
The matrix ranK of A is :  3
Basis for the null space of A:
[[-0.389]
 [ 0.405]
 [-0.738]
 [-0.373]]


Some Extra work

In [11]:


from sympy import Matrix ,init_printing
init_printing()
A = Matrix([[1, -2, 9, 5, 4,], [1, -1, 6, 5, -3], [-2, 0, -6, 1, -2],
[4, 1, 9, 1, -9]])
A



⎡1   -2  9   5  4 ⎤
⎢                 ⎥
⎢1   -1  6   5  -3⎥
⎢                 ⎥
⎢-2  0   -6  1  -2⎥
⎢                 ⎥
⎣4   1   9   1  -9⎦

In [12]:
X=A.rref()
X

⎛⎡1  0  3   0  0 ⎤           ⎞
⎜⎢               ⎥           ⎟
⎜⎢0  1  -3  0  -7⎥           ⎟
⎜⎢               ⎥, (0, 1, 3)⎟
⎜⎢0  0  0   1  -2⎥           ⎟
⎜⎢               ⎥           ⎟
⎝⎣0  0  0   0  0 ⎦           ⎠

In [13]:
ref, pivot_cols = A.rref()
print(ref, pivot_cols)

Matrix([[1, 0, 3, 0, 0], [0, 1, -3, 0, -7], [0, 0, 0, 1, -2], [0, 0, 0, 0, 0]]) (0, 1, 3)


In [14]:
A.nullspace()



⎡⎡-3⎤  ⎡0⎤⎤
⎢⎢  ⎥  ⎢ ⎥⎥
⎢⎢3 ⎥  ⎢7⎥⎥
⎢⎢  ⎥  ⎢ ⎥⎥
⎢⎢1 ⎥, ⎢0⎥⎥
⎢⎢  ⎥  ⎢ ⎥⎥
⎢⎢0 ⎥  ⎢2⎥⎥
⎢⎢  ⎥  ⎢ ⎥⎥
⎣⎣0 ⎦  ⎣1⎦⎦

In [15]:
range_space_basis = A[:, pivot_cols]
print(range_space_basis )

Matrix([[1, -2, 5], [1, -1, 5], [-2, 0, 1], [4, 1, 1]])


In [16]:
import numpy as np
from scipy.linalg import svd

# Define the matrix A
A = np.array([[1, -2, 9, 5, 4], [1, -1, 6, 5, -3], [-2, 0, -6, 1, -2], [4, 1, 9, 1, -9]])

# Compute the SVD of A
U, S, Vt = svd(A)

# Find the null space from the SVD
null_space = Vt.T[:, np.where(S < 1e-10)[0]]

print("Null Space of A:")
print(null_space)


Null Space of A:
[[-0.872]
 [ 0.357]
 [ 0.291]
 [-0.147]
 [-0.074]]
