In [1]:
#NumPy, short for "Numerical Python," is a fundamental library in the Python programming language
#used for numerical and scientific computing. It provides support for large, multi-dimensional arrays
#and matrices, along with a collection of mathematical functions to operate on these arrays

In [2]:
# An Advantages of using Numpy array
# consumes less meomery
#fast as compare to the python list

In [3]:
# importance of Numpy in Python
# wide vairty of mathematical operations on array
#It supplies an enormous library of high level mathematical functions that operates on these arrays and matrics
# mathematical , logical ,shape manipulation ,sorting ,selecting ,I/O ,discrete Fourier Transformation ,basis linear algebra ,basic statisical
#operations,random simulation and much more (use of numpy )

In [4]:
import numpy as np
import math

In [6]:
A = [0.1, 1.3, 0.4, 0.5] #  Declaration of list
a = np.array(A) #  Create of numpy  array
print(a)
print(A)
print(type(a))
print(type(A))
%timeit [j**4 for j in range(1,9)]
%timeit np.arange(1,9)**4 # we crating a numpy array i using a 'arange' function ,creating a array from starting to ending point

[0.1 1.3 0.4 0.5]
[0.1, 1.3, 0.4, 0.5]
<class 'numpy.ndarray'>
<class 'list'>
2.63 µs ± 42.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
2.37 µs ± 38.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [7]:
l=[]
for i in range(1,5):
   int_1=int(input("enter the value:")) # Asking to users to enter the value
   l.append(int_1)
print(np.array(l))


enter the value:12
enter the value:23
enter the value:34
enter the value:45
[12 23 34 45]


In [8]:
a.dtype # a's common element type (A.dtype is undefined!)

dtype('float64')

In [9]:
2*a # numpy array multiply by 2

array([0.2, 2.6, 0.8, 1. ])

In [11]:
2*A # array multiply by 2

[0.1, 1.3, 0.4, 0.5, 0.1, 1.3, 0.4, 0.5]

In [21]:
n = 100000
x = np.linspace(0, 2*np.pi, n)

In [22]:
# list comprehension
%timeit y = [math.sin(x[i]) * math.exp(-x[i]) for i in range(n)]
# use numpy ufuncs
%timeit y = np.sin(x) * np.exp(-x)

54.4 ms ± 728 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
2.59 ms ± 73.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [23]:
def f(v): # apply f to one scalar value v
    return math.sin(v) * math.exp(-v)

In [24]:
vectorizedf = map(f, x) # apply same f to a vector of values x

In [25]:
F = np.vectorize(f) # F can be applied to a array x

In [26]:
# use map
%timeit y = list(map(f, x))
# use numpy's vectorize
%timeit y = F(x)
# use numpy's ufunc
%timeit y = np.sin(x) * np.exp(-x)

38 ms ± 776 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
36.2 ms ± 777 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
2.8 ms ± 538 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [27]:
%timeit for x in range(1000000): x**3
%timeit for x in np.arange(1000000): x**3

331 ms ± 4.08 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
154 ms ± 45.3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [29]:
a = np.random.randint(0,9,5) # taking a random  5-elements array between 0 to 9
a


array([1, 5, 2, 5, 3])

In [35]:
a[::]

array([1, 5, 2, 5, 3])

In [34]:
a[-3:]  # it is sub_array of 'a' which copy the element from "a" from starting index 3 to last

array([2, 5, 3])

In [37]:
a[-1], a[len(a)-1] # a[-1], a[len(a)-1] to use exteact last element of any array

(3, 3)

In [38]:
a[-4:-1:2]

array([5, 5])

In [39]:
slice = range(-4,-1,2) # Think of b:e:s specification as a range.
a[-4:-1:2], a[slice] # In older versions, a[slice] may not work
# but will work with slice=arange(-4,-1,2).


(array([5, 5]), array([5, 5]))

In [40]:
a = np.array([1,2,3])
b = np.array([3,4,5,6])

In [41]:
a = b
a[0] = 1
a

array([1, 4, 5, 6])

In [42]:
b

array([1, 4, 5, 6])

In [43]:
a = np.array([1,2,3]) # This is Object1 and "a" is a name for it.
b = np.array([3,4,5,6]) # This is Object2 and "b" is a name for it

In [44]:
id(a), id(b)

(140083299972368, 140083299973328)

In [45]:
a = b # a is no longer a name for Object1, it is now a name for Object2.

In [46]:
id(a), id(b)

(140083299973328, 140083299973328)

In [47]:
a = np.array([1,2,3]) # Object1
b = np.array([3,4,5,6]) # Object2
a = b.copy() # Copies Object2, and binds a to the copy
a[0] = 2 # Only the copied (new) object is changed

In [48]:
a, b

(array([2, 4, 5, 6]), array([3, 4, 5, 6]))

In [49]:
Amat = [[1,2],
[3,4]]
Amat


[[1, 2], [3, 4]]

In [ ]:
amat = np.array(Amat)
amat


In [51]:
type(A), type(a)

(list, numpy.ndarray)

In [52]:
2*Amat

[[1, 2], [3, 4], [1, 2], [3, 4]]

In [53]:
amat

array([[1, 2],
       [3, 4]])

In [54]:
amat * amat

array([[ 1,  4],
       [ 9, 16]])

In [55]:
import sys
print(sys.version) # check if you have version >= 3.5 before trying @

3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]


In [56]:
 amat @ amat

array([[ 7, 10],
       [15, 22]])

In [57]:
np.dot(amat, amat) # dot(A,B) = matrix A multiplied by matrix B

array([[ 7, 10],
       [15, 22]])

In [59]:

amat.dot(amat)


array([[ 7, 10],
       [15, 22]])

In [60]:
amat**2 # not equal to matrix power !!

array([[ 1,  4],
       [ 9, 16]])

In [61]:
np.linalg.matrix_power(amat, 2)#Numpy provides a matrix_power routine to compute Mn for matrices M (and integers n)

array([[ 7, 10],
       [15, 22]])

In [62]:
#how to slice 2D array
A = np.array([[7, 8, 5, 1], [2, 5, 5, 2], [9, 6, 8, 9]])
A


array([[7, 8, 5, 1],
       [2, 5, 5, 2],
       [9, 6, 8, 9]])

In [63]:
A[1, :], A[:, 2]

(array([2, 5, 5, 2]), array([5, 5, 8]))

In [64]:
A[:3:2, :3]

array([[7, 8, 5],
       [9, 6, 8]])

In [ ]:
#How are 2D arrays stored?
M = np.array([[7, 8, 5, 1], [2, 5, 5, 2], [9, 6, 8, 9]])
M

In [66]:
M.reshape(2, 6) # Just a different view of the same data

array([[7, 8, 5, 1, 2, 5],
       [5, 2, 9, 6, 8, 9]])

In [ ]:
M.ravel() # The 1D data of M in row-major ordering

array([7, 8, 5, 1, 2, 5, 5, 2, 9, 6, 8, 9])

In [67]:
A = np.array(M, order='F')
A

array([[7, 8, 5, 1],
       [2, 5, 5, 2],
       [9, 6, 8, 9]])

In [68]:
A.ravel(order='A') # A's internal ordering is Fortran style

array([7, 2, 9, 8, 5, 6, 5, 5, 8, 1, 2, 9])

In [69]:
M.ravel(order='A') # M's internal ordering is default C-style

array([7, 8, 5, 1, 2, 5, 5, 2, 9, 6, 8, 9])

In [72]:
#Can I put booleans as indices?
#If a numpy array is given indices that are boolean (instead of integers), then rows or
#columns are selected based on True indices. This is called masking. It is very useful
#together with vectorized conditionals.
N = np.arange(25).reshape(5,5)
N

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [73]:
mask = (N>7) & (N<18)
mask

array([[False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True, False, False],
       [False, False, False, False, False]])

In [74]:
N[mask]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [75]:
i, j = np.where(mask) # Returns i and j indices where mask[i,j] is True.
i, j # 1st True value of mask is at i[0],j[0],
# 2nd True value of mask is at i[1],j[1], etc.

(array([1, 1, 2, 2, 2, 2, 2, 3, 3, 3]), array([3, 4, 0, 1, 2, 3, 4, 0, 1, 2]))

In [76]:
#How do I represent higher order tensors?
#Numpy can work with general-dimensional arrays, not just 1D or 2D arrays.
# For an ndimensional array, the shape of a numpy array is a tuple of n integers giving the sizes in
#each dimension.

In [77]:
data = np.random.randint(low=0, high=10, size=30) # 1D array

In [78]:
T2 = np.reshape(data, (6, 5)) # 2D array
T2


array([[8, 7, 5, 2, 3],
       [3, 2, 6, 6, 9],
       [3, 5, 6, 5, 5],
       [0, 0, 5, 3, 4],
       [9, 6, 1, 1, 6],
       [0, 1, 0, 1, 9]])

In [79]:
T3 = np.reshape(data, (2, 3, 5)) # 3D array
T3

array([[[8, 7, 5, 2, 3],
        [3, 2, 6, 6, 9],
        [3, 5, 6, 5, 5]],

       [[0, 0, 5, 3, 4],
        [9, 6, 1, 1, 6],
        [0, 1, 0, 1, 9]]])

In [80]:
print('T3 is a ', T3.ndim, 'dimensional array of shape ', T3.shape)
print('T2 is a ', T2.ndim, 'dimensional array of shape ', T2.shape)
print('data is a ', data.ndim, 'dimensional array of shape ', data.shape)

T3 is a  3 dimensional array of shape  (2, 3, 5)
T2 is a  2 dimensional array of shape  (6, 5)
data is a  1 dimensional array of shape  (30,)
